
version: '3.7'
services:
  # Postgres
  db:
    image: postgres
    env_file:
      - env.dev
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data/
    networks:
      - main  # Add the container to the network "main"

  apps:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - env.dev
    command: python3 manage.py runserver 0.0.0.0:8000
    ### command: gunicorn --pythonpath apps _config.wsgi --bind 0.0.0.0:8000
    entrypoint: ../docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - main  # Add the container to the network "main"
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - main  # Add the container to the network "main"

  celery:
    build: .
    env_file:
      - env.dev
    command: celery -A _apps worker -l info
    volumes:
      - .:/code
    networks:
      - main  # Add the container to the network "main"
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    env_file:
      - env.dev
    command: celery -A _apps beat -l info
    volumes:
      - .:/code
    networks:
      - main  # Add the container to the network "main"
    depends_on:
      - db
      - redis

networks:
  main:
